### ISSUE TITLE
This is pretty cool!

### ISSUE THREAD

**Issue by jamesbraza** [jsh9/cercis#37]
Thanks for making this!  I think the community needs more highly configurable tools like this, not prioritizing style opinions. Another similar project is https://github.com/grantjenks/blue, but this one is actively maintained. Cheers!

**Comment by jsh9** [comment]
Thanks!  Keeping this tool up to date turns out to be non trivial.  So I'm really hoping the authors of Ruff can make it more configurable than Black.
